package presentation.navigation.directions

import androidx.navigation.NavGraphBuilder
import androidx.navigation.compose.composable
import presentation.character.screen.CharacterScreen
import presentation.character.viewmodel.CharacterViewModel
import presentation.util.ConstantNavigator

